### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RedSkittleFox** [redhatdragon/YearsOfShadow#3]
- [x] Remove unused files
- [x] Refactor code - remove commented out code, move implementations to source files
- [x] Refactor includes, use <> instead ""
- [x] Introduce namespaces
- [x] Add documentation
- [x] Add google test and google benchmark
- [x] Implement ImGUI
- [x] Implement logging
